#!/bin/bash

echo "🚀 GitHub Pages Deployment Guide"
echo "================================"
echo ""
echo "To deploy your portfolio to GitHub Pages:"
echo ""
echo "1. Create a new repository on GitHub:"
echo "   - Name it: temitayocharles.github.io (for personal site)"
echo "   - Or: ultimate-devops-portfolio (for project site)"
echo ""
echo "2. Initialize git and push your code:"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial portfolio commit'"
echo "   git branch -M main"
echo "   git remote add origin https://github.com/temitayocharles/[REPO-NAME].git"
echo "   git push -u origin main"
echo ""
echo "3. Enable GitHub Pages:"
echo "   - Go to repository Settings"
echo "   - Scroll to 'Pages' section"
echo "   - Select 'Deploy from a branch'"
echo "   - Choose 'main' branch"
echo "   - Select '/ (root)' folder"
echo "   - Click Save"
echo ""
echo "4. Your site will be available at:"
echo "   https://temitayocharles.github.io"
echo ""
echo "✅ Portfolio Features Included:"
echo "   - Professional About Me page"
echo "   - Skills showcase with visual indicators"
echo "   - Multiple DevOps projects"
echo "   - Mobile-responsive design"
echo "   - SEO optimized"
echo "   - Professional contact information"
echo "   - Social media integration"
echo ""
echo "📁 Current files in your portfolio:"
ls -la *.html | wc -l | xargs echo "   HTML pages:"
echo "   - index.html (Homepage)"
echo "   - about-me.html (Personal profile)"
echo "   - projects.html (DevOps projects)"
echo "   - skills.html (Technical skills)"
echo "   - blog.html (Future articles)"
echo "   - contact.html (Contact info)"
echo "   - Plus technical project pages"
echo ""
echo "🎯 Your portfolio is now competitive with top DevOps engineers!"
