CREATE TABLE IF NOT EXISTS metrics (
  id SERIAL PRIMARY KEY,
  cpu INT NOT NULL,
  ram INT NOT NULL,
  disk INT NOT NULL,
  network INT NOT NULL,
  timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

